### ISSUE TITLE
Crash when recording certain items to queue

### ISSUE THREAD

**Issue by Spiderach** [hjake123/lost-and-found#5]
It seems that some items cause a crash when Lost and Fished tries to add them to the fishable queue.

Specifically, the alternate eyes of ender from End Remastered cause it.

Crash report attached.
[crash-2023-04-07_15.18.25-server.txt](https://github.com/hjake123/lost-and-found/files/11181307/crash-2023-04-07_15.18.25-server.txt)

**Comment by hjake123** [comment]
It seems like those items can exist with 0 durability, which I didn't expect to be possible. Should be patched with the next update.
